version: "3"

services:
  webapp:
    build: ..
    networks:
      - mongod-net
    ports:
      - '5000:5000'
  
  mongodb:
    image: mongo:3.2.20-jessie
    networks:
      - mongod-net
    ports:
      - '27017:27017'


networks:
  mongod-net:
    driver: bridge